import * as config from '../config'
import { generateContext, generateRoot } from './generate-root'

const root = generateRoot(config)
const context = generateContext(config)

const banner = `/*
 * THIS FILE IS GENERATED BY setup-styles.ts
 * DO NOT EDIT IT DIRECTLY.
 */`
const lintIgnore =
  '/* biome-ignore-all lint/suspicious/noUnknownAtRules: generated PostCSS custom media declarations */'

const rootcss = [banner, lintIgnore, root]
const contextcss = [banner, lintIgnore, context]

await Bun.write('./lib/styles/css/root.css', rootcss.join('\n\n'))
await Bun.write('./lib/styles/css/context.css', contextcss.join('\n\n'))

console.log(
  Bun.color('green', 'ansi'),
  '✓',
  Bun.color('black', 'ansi'),
  'Style config generated successfully'
)
