'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/moon.glb -o components/effects/moon.tsx -t -r /models/ 
*/

import type * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useFrame, type ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Moon_Cube002: THREE.Mesh
  }
  materials: {
    Moon: THREE.MeshStandardMaterial
  }
}

export function Moon(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/moon.glb') as unknown as GLTFResult
  const ref = useRef<THREE.Group>(null)

  useFrame((state) => {
    if (ref.current) {
      ref.current.rotation.y = state.clock.elapsedTime * 0.05
      ref.current.position.y = Math.sin(state.clock.elapsedTime * 0.5) * 0.1
    }
  })

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.Moon_Cube002.geometry} material={materials.Moon} />
    </group>
  )
}

useGLTF.preload('/models/moon.glb')
